/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Entities.Playlist;
import java.util.List;

/**
 *
 * @author Sala BD
 */
public class PanelAgregarAPlaylist extends javax.swing.JPanel
{

    /**
     * Creates new form PanelAgregarAPlaylist
     */
    private Menu ventana;
 
   public PanelAgregarAPlaylist(Menu ventana)
    {
        
       initComponents();
       jButtonCrear.setEnabled(false);
       jTextNuevoNombre.setEnabled(false);
       this.ventana = ventana;       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButtonAgregar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonCreala = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextNuevoNombre = new javax.swing.JTextField();
        jButtonCrear = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione la playlist para agregar la(s) canción(es)");

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jLabel2.setText("¿No tienes playlist todavía?");

        jButtonCreala.setText("¡Crea una!");
        jButtonCreala.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonCrealaActionPerformed(evt);
            }
        });

        jLabel3.setText("Ingresa el nuevo nombre de tu playlist");

        jButtonCrear.setText("Crear");
        jButtonCrear.setEnabled(false);
        jButtonCrear.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonCrearActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Publica", "Privada" }));
        jComboBox2.setEnabled(false);
        jComboBox2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Ingrese la privacidad de la playlist");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonAgregar))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonCreala)
                                    .addComponent(jTextNuevoNombre)))))
                    .addComponent(jButtonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonCreala))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14)
                .addComponent(jButtonCrear)
                .addContainerGap(143, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAgregarActionPerformed
    {//GEN-HEADEREND:event_jButtonAgregarActionPerformed

        ventana.agregarAPlaylist((Playlist)jComboBox1.getSelectedItem());
        
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonCrealaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCrealaActionPerformed
    {//GEN-HEADEREND:event_jButtonCrealaActionPerformed
        jButtonAgregar.setEnabled(false);
        jButtonCreala.setEnabled(false);
        jComboBox1.setEnabled(false);
        jTextNuevoNombre.setEnabled(true);
        jButtonCrear.setEnabled(true);      
        jComboBox2.setEnabled(true);
    }//GEN-LAST:event_jButtonCrealaActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCrearActionPerformed
    {//GEN-HEADEREND:event_jButtonCrearActionPerformed
   
        Playlist playlist = ventana.AgregarPlaylist( jTextNuevoNombre.getText(), (String)jComboBox2.getSelectedItem());
        jComboBox1.addItem(playlist);
        repaint();
        jButtonAgregar.setEnabled(true);
        jButtonCreala.setEnabled(true);
        jComboBox1.setEnabled(true);
        jTextNuevoNombre.setEnabled(false);
        jButtonCrear.setEnabled(false);      
        jComboBox2.setEnabled(false);
        ventana.cambiarPanel("Menu Principal");

    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBox1ActionPerformed
    {//GEN-HEADEREND:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBox2ActionPerformed
    {//GEN-HEADEREND:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonCreala;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JComboBox<Playlist> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextNuevoNombre;
    // End of variables declaration//GEN-END:variables

    void actualizarPlaylists(List<Playlist> playlists)
    {
        jComboBox1.removeAllItems();
        for (Playlist playlist : playlists)
        {
            jComboBox1.addItem(playlist);
        }
    }
}
